language: ruby
cache: bundler
dist: xenial

branches:
  only:
    - master

bundler_args: --jobs 7 --without docs debug

before_install: gem install bundler -v 1.10.6

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6
